# Caracterização

Este curso é uma iniciativa particular mas aberto a qualquer interessado.

## Objetivos do Curso

No fim deste curso, deveremos ser capazes de:

1) Entender os princípios do _DataOps_:

    - Compreender como uma abordagem _DataOps_ melhora o desenvolvimento, a colaboração e a automação em projetos de dados.
    - Aplicar os conceitos fundamentais de _DataOps_ em diferentes contextos (público, privado, académico).

1) Utilizar o Git para o controlo de versões e para colaboração:

    - Implementar controle de versões em projetos de dados usando Git.
    - Colaborar de forma eficaz em projetos de dados, gerir mudanças e contribuir em equipa de forma integrada.

1) Automatizar Fluxos de Trabalho com R:

    - Criar e automatizar _scripts_ em R para análises reprodutíveis e eficientes.
    - Utilizar boas práticas de programação e automação em ciência de dados.
    
1) Gerar Documentação reprodutível com Quarto:

    - Criar Dashboards dinâmicos e interativos utilizando Quarto.
    - Integrar Quarto com Git para versionamento e automação de documentos em pipelines de dados.
    
1) Implementar um Pipeline de _DataOps_ completo:

    - Combinar R, Git e Quarto para construir um pipeline automatizado de _DataOps_.
    - Entregar resultados confiáveis e reprodutíveis de forma contínua em projetos de ciência de dados.
    
## Pré-requisitos

Este curso foi desenhado para estudantes e profissionais que desejam aprender como aplicar os princípios de _DataOps_ em projetos de ciência de dados, automatizando fluxos de trabalho e garantindo a reprodutibilidade dos resultados. Para acompanhar o conteúdo de forma eficaz, é recomendável que  os participantes tenham os seguintes conhecimentos:

1) Familiaridade com R:

    - O curso utilizará o R como a principal linguagem de programação para análise de dados. É desejável que os participantes tenham uma familiaridade básica com R, incluindo a criação de _scripts_ simples e o uso de pacotes.
    - No entanto, mesmo que não sejam utilizadores fluentes em R, poderão acompanhar o curso, pois serão dados exemplos claros e práticos.

1) Noções de Git (não obrigatório, mas recomendável):

    - Ter uma compreensão inicial de controlo de versões com Git será útil, mas o curso incluirá uma introdução à ferramenta, de modo que iniciantes poderão aprender os conceitos e aplicar as práticas ao longo do curso.
    
1) Curiosidade e disposição para aprender:

    - Este curso tem uma abordagem prática, portanto, a curiosidade e a vontade de aprender a usar novas ferramentas e metodologias são essenciais. Iremos guiar os participantes passo a passo no uso de R, Git e Quarto, mostrando como estas ferramentas podem ser integradas em um pipeline eficiente de _DataOps_.
