project:
  type: book
  output-dir: docs
book:
  title: Princípios básicos de DataOps
  author: Bruno A Lima
  date: '2024-10-20'
  search: true
  repo-url: https://github.com/balima78/DataOpsMOOC
  repo-actions:
  - edit
  - issue
  repo-branch: main
  favicon: images/coverDOB.jfif
  issue-url: https://github.com/balima78/DataOpsMOOC/issues
  chapters:
  - index.qmd
  - 101-intro.qmd
  - 102-caracteriza.qmd
  - 201-instal.qmd
  - 202-materia.qmd
  - 203-dash.qmd
  - 204-versoes.qmd
  - 205-renv.qmd
  - 206-pub.qmd
  - 800-avaliacao.qmd
  - 900-summary.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt
